import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { AlertTriangle } from "lucide-react";

export const metadata: Metadata = {
  title: "Medical Disclaimer — Drift Sleep",
  description:
    "Medical disclaimer for Drift Sleep. Our sleep calculators and AI coaching are for informational purposes only and do not constitute medical advice.",
  alternates: {
    canonical: "/medical-disclaimer",
  },
  openGraph: {
    title: "Medical Disclaimer — Drift Sleep",
    description:
      "Drift Sleep tools are for informational purposes only and do not constitute medical advice.",
    url: "/medical-disclaimer",
    siteName: "Drift Sleep",
  },
};

export default function MedicalDisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 md:px-8 py-10 md:py-16">
      <Breadcrumbs
        items={[
          { label: "Home", href: "/" },
          { label: "Medical Disclaimer", href: "/medical-disclaimer" },
        ]}
      />

      <div className="flex items-center gap-3 mt-8 mb-6">
        <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-[#fdcb6e]/10">
          <AlertTriangle className="w-5 h-5 text-[#fdcb6e]" />
        </div>
        <h1 className="text-3xl md:text-4xl font-bold font-headline text-on-surface">
          Medical Disclaimer
        </h1>
      </div>

      <div className="space-y-6">
        <div className="glass-card rounded-2xl p-6 border border-[#fdcb6e]/20">
          <p className="text-on-surface leading-relaxed font-medium">
            Drift Sleep and all tools on sleepcyclecalc.com are for
            informational and educational purposes only. Nothing on this website
            constitutes medical advice, diagnosis, or treatment.
          </p>
        </div>

        <section>
          <h2 className="text-xl font-bold font-headline text-on-surface mb-3">
            Not a Medical Device
          </h2>
          <p className="text-on-surface-variant leading-relaxed">
            Our sleep calculators, AI Sleep Coach, trend analysis, and all other
            features are tools for general wellness education. They are not
            FDA-cleared or CE-marked medical devices. The results and
            recommendations generated by these tools should not be used as a
            substitute for professional medical judgment.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold font-headline text-on-surface mb-3">
            Wearable Device Data
          </h2>
          <p className="text-on-surface-variant leading-relaxed">
            Sleep data imported from wearable devices (Oura, Fitbit, WHOOP,
            Apple Health) is consumer-grade and may not be clinically accurate.
            Metrics such as sleep stages, heart rate variability, and blood
            oxygen levels from consumer wearables have varying degrees of
            accuracy compared to clinical polysomnography.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold font-headline text-on-surface mb-3">
            AI-Generated Content
          </h2>
          <p className="text-on-surface-variant leading-relaxed">
            Our AI Sleep Coach provides general wellness suggestions based on
            your sleep data patterns. AI-generated advice is not reviewed by
            medical professionals before delivery and may not account for your
            complete health history, medications, or medical conditions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold font-headline text-on-surface mb-3">
            When to See a Doctor
          </h2>
          <p className="text-on-surface-variant leading-relaxed mb-3">
            You should consult a qualified healthcare provider if you experience:
          </p>
          <ul className="list-disc list-inside text-on-surface-variant space-y-1.5 ml-2">
            <li>Persistent difficulty falling or staying asleep</li>
            <li>Excessive daytime sleepiness despite adequate sleep time</li>
            <li>Loud or chronic snoring, especially with pauses in breathing</li>
            <li>Restless legs or involuntary movements during sleep</li>
            <li>Significant changes in your sleep patterns</li>
            <li>Sleep problems that affect your daily functioning</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold font-headline text-on-surface mb-3">
            Research Citations
          </h2>
          <p className="text-on-surface-variant leading-relaxed">
            Sleep recommendations referenced on this site are based on
            guidelines from the National Sleep Foundation, the American Academy
            of Sleep Medicine, the Centers for Disease Control and Prevention
            (CDC), and peer-reviewed sleep research. These guidelines represent
            general population averages and may not apply to every individual.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold font-headline text-on-surface mb-3">
            Limitation
          </h2>
          <p className="text-on-surface-variant leading-relaxed">
            By using Drift Sleep, you acknowledge that the information provided
            is not a substitute for professional medical advice. We assume no
            liability for health decisions made based on information from this
            website.
          </p>
        </section>
      </div>
    </div>
  );
}
